### ISSUE TITLE
Missing support for latest draft 13

### ISSUE THREAD

**Issue by cre8** [Sphereon-Opensource/OID4VCI#109]
@TimoGlastra  @nklomp To be aligned with the latest version of the [spec](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#appendix-F-2), it would help to know what is the current supported version (I assume it is 11 based on the open issues)

I remember that this SDK tries to support all drafts, when is it planned to drop it? I would love to help so other systems can interact with software based on this package

**Comment by cre8** [comment]
Suggestion: we are removing support for all versions below 13 and publish it under a new major version. This will bot break current systems when they updating according to semv versioning.

**Comment by nklomp** [comment]
Yeah, we will do that over the next few months. We do have to support DIIP, Mosip and Entra, so we cannot go there directly, as our solutions need to support these versions simultaniously. But the nice thing is that the reference implementation, DIIP v3 in Aug and other parties are moving to similar versions of the specs. So before that we will start on new major versions where we drop the older versions

**Comment by nklomp** [comment]
One thing we want to do is move towards a strategy pattern for version support and do more validations with something like joi.
V13 support will land shortly. 
We haven't created a first stable version yet, but if you want to take a stab at dropping pre v13 in a v1-next branch using the above pointers, we are of course more than happy to work together with you on that

**Comment by cre8** [comment]
I like the discovery approach. But when OID4VCI is leaving the draft phase I think it's okay to create a version that only includes the final version. The removal of "deprecated" versions will increase security and auditability of the library.

**Comment by nklomp** [comment]
Yeah for sure. Also moving towards a strategy pattern, means we can simply have the version code in complete separate folders and packages. Then it is just deleting them as we go. But as soon as a stable version emerges, we for sure would move to drop all of the draft versions. I just want to keep the infra for version discovery so we can also have new final or draft versions of the specs over time one we hit a stable version. But then we don't repeat the current approach of having so much logic constantly having to take into account the different versions etc. Simple detect it and then go into complete seperate code paths from that point on,

**Comment by nklomp** [comment]
Okay, this took longer than we hoped, but current version has ID 1 / Draft 13 support. We will start on a new 1.x.x. branch shortly where we will do some refactoring and drop everything below draft 13
