### ISSUE TITLE
`determineSpecVersionFromURI` error

### ISSUE THREAD

**Issue by martines3000** [Sphereon-Opensource/OID4VCI#47]
While trying to use the library, I am getting and error from the `determineSpecVersionFromURI` function.

Error:

`Error: Invalid param. Some keys have been used from version: 1011 version while 'pre-authorized_code' is used from version: 1009`

The error occurs with the following URI:
`openid-credential-offer://credential_offer?credential_issuer=http%3A%2F%2F127.0.0.1%3A3003&credentials%5B0%5D=GmCredential&grants%5Burn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Apre-authorized_code%5D%5Bpre-authorized_code%5D=38ea2b4a-ea85-4d52-8e59-937b52218a89`

I think this [line](https://github.com/Sphereon-Opensource/OID4VCI/blob/75ea2a7a3e9df347aa1ee9428c3e16e702542e62/packages/common/lib/functions/CredentialOfferUtil.ts#LL9C15-L9C25) of the code is the problem, because both the `VER_1_0_09` and `VER_1_0_11` use the `pre-authorized_code`.

**Comment by nklomp** [comment]
Thanks for the report. The logic has been changed around a bit. We have a refactor on the backlog as current version detection is a little brittle anyway.

Latest feature/issuer branch which has unstable npmjs releases should work against v11, solving this issue. Please reopen if you still encounter the same issue
