### ISSUE TITLE
`getIssuerFromCredentialOfferPayload` error

### ISSUE THREAD

**Issue by martines3000** [Sphereon-Opensource/OID4VCI#48]
While trying to use the library, I am getting and error from the `getIssuerFromCredentialOfferPayload`  function.

Error:

`Error: can't retrieve metadata from CredentialOfferRequest. No issuer field is present`

The error occurs with the following URI:
`openid-credential-offer://credential_offer?credential_issuer=http%3A%2F%2F127.0.0.1%3A3003&credentials%5B0%5D=GmCredential&grants%5Burn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Apre-authorized_code%5D%5Bpre-authorized_code%5D=38ea2b4a-ea85-4d52-8e59-937b52218a89`

I think this [line](https://github.com/Sphereon-Opensource/OID4VCI/blob/75ea2a7a3e9df347aa1ee9428c3e16e702542e62/packages/common/lib/functions/CredentialOfferUtil.ts#L54) of the code is the problem.

**Comment by nklomp** [comment]
Hi @martines3000 you are correct.

Unfortunately, it seems like you are working against a v10+ issuer. The client only supports v8 and v9 and this point as these are the most common versions in the wild right now

 We are however pretty far along with our own v11 issuer, meaning we do have all the v11 payloads and interfaces.
V11 client support is expected to land and work somewhere next week.

**Comment by nklomp** [comment]
The exact same fix (nice little Demorgan error) has been created in the latest feature branch. Although that will indeed solve the problem, you will run into other errors, simply because the payloads have changed

**Comment by nklomp** [comment]
Latest feature/issuer branch which has unstable npmjs releases should work against v11, solving this issue. Please reopen if you still encounter the same issue
