### ISSUE TITLE
OIDC4VCI is not passing endpointOpts.getCrendentialOfferOpts

### ISSUE THREAD

**Issue by ragnika** [Sphereon-Opensource/OID4VCI#73]
https://github.com/Sphereon-Opensource/OID4VCI/blob/e530d5502f8336ff048fce8f08c46dd8f44a646f/packages/issuer-rest/lib/OID4VCIServer.ts#L114

`opts?.getCredentialOfferOpts` is passed instead of `opts?.endpointOpts.getCredentialOfferOpts`

**Comment by ragnika** [comment]
opened a small PR to fix this
https://github.com/Sphereon-Opensource/OID4VCI/pull/74

**Comment by nklomp** [comment]
Sorry for the late reply and thanks for the fix 👍
