### ISSUE TITLE
Re-run CI on main to publish new `.next` version

### ISSUE THREAD

**Issue by TimoGlastra** [Sphereon-Opensource/OID4VCI#90]
It seems the E2E test failed meaning the change in #87 is not release as `.next` version. Could the CI be re-ran so we can update our oid4vci package?

https://github.com/Sphereon-Opensource/OID4VCI/actions/runs/7877088800/job/21492675963

**Comment by sanderPostma** [comment]
Hi @TimoGlastra 

> 
> Successfully published:
>  - @sphereon/oid4vci-callback-example@0.8.2-next.48+81adb47
>  - @sphereon/oid4vci-client@0.8.2-next.48+81adb47
>  - @sphereon/oid4vci-common@0.8.2-next.48+81adb47
>  - @sphereon/oid4vci-issuer@0.8.2-next.48+81adb47

**Comment by nklomp** [comment]
Okay we have an issue in our infra anyway. A new .next release has just been published, which should have many fixes
